# Generated by Django 5.2.17 on 2026-08-18 16:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceSummary',
            fields=[
                ('compliance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('policy_compliance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('training_compliance', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='compliance_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_summary',
                'ordering': ['-employee_score'],
            },
        ),
    ]
