# Generated by Django 5.2.17 on 2026-08-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancesummary',
            name='pos_check_compliance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
