# Generated by Django 5.2.17 on 2026-08-17 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('policy_type', models.CharField(choices=[('POS Security', 'POS Security'), ('Password & Account Security', 'Password & Account Security'), ('Incident Reporting', 'Incident Reporting'), ('Data Protection & Privacy', 'Data Protection & Privacy'), ('Acceptable Use', 'Acceptable Use Policy'), ('Removable Media & USB Security', 'Removable Media & USB Security'), ('Security Awareness & Training', 'Security Awareness & Training'), ('Admin Access Control', 'Admin Access Control'), ('Policy Management & Administration', 'Policy Management & Administration'), ('Employee Data & Compliance Access', 'Employee Data & Compliance Access'), ('Audit Log & Monitoring', 'Audit Log & Monitoring')], db_index=True, max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policies',
                'ordering': ['title', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyAcknowledgement',
            fields=[
                ('acknowledgement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='policies.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'policy_acknowledgements',
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['status'], name='policies_status_d09338_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_type'], name='policies_policy__66f050_idx'),
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('title', 'version'), name='unique_policy_title_version'),
        ),
        migrations.AddConstraint(
            model_name='policyacknowledgement',
            constraint=models.UniqueConstraint(fields=('policy', 'user'), name='unique_policy_user_acknowledgement'),
        ),
    ]
