# Generated by Django 5.2.17 on 2026-08-17 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSTerminal',
            fields=[
                ('pos_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('terminal_code', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['terminal_code'],
            },
        ),
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('shift_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('shift_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('opening_cash', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_in', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_out', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('closing_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cash_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('handover_time', models.DateTimeField(blank=True, null=True)),
                ('handover_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Completed', 'Completed')], db_index=True, default='Open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handed_over_to', models.ForeignKey(blank=True, db_column='handed_over_to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_pos_handovers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, related_name='pos_shifts', to=settings.AUTH_USER_MODEL)),
                ('pos', models.ForeignKey(db_column='pos_id', on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='pos_security.posterminal')),
            ],
            options={
                'db_table': 'pos_shifts',
                'ordering': ['-shift_start'],
            },
        ),
        migrations.CreateModel(
            name='DailySecurityCheck',
            fields=[
                ('check_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_unknown_device_present', models.BooleanField()),
                ('is_unusual_behavior_observed', models.BooleanField()),
                ('is_physically_secure', models.BooleanField()),
                ('is_credentials_secure', models.BooleanField()),
                ('is_suspicious_surroundings', models.BooleanField()),
                ('result', models.CharField(choices=[('Normal', 'Normal'), ('Suspicious', 'Suspicious')], db_index=True, max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shift', models.OneToOneField(db_column='shift_id', on_delete=django.db.models.deletion.CASCADE, related_name='security_check', to='pos_security.posshift')),
            ],
            options={
                'db_table': 'daily_security_checks',
            },
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['user'], name='pos_shifts_user_id_35e482_idx'),
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['pos'], name='pos_shifts_pos_id_b1ea8b_idx'),
        ),
        migrations.AddIndex(
            model_name='posshift',
            index=models.Index(fields=['status'], name='pos_shifts_status_0a451e_idx'),
        ),
    ]
