# Generated by Django 5.2.17 on 2026-08-18 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('training', '0002_quizattempt_quizquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingNeed',
            fields=[
                ('need_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], db_index=True, max_length=10)),
                ('identified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Addressed', 'Addressed')], db_index=True, default='Open', max_length=15)),
                ('training', models.ForeignKey(db_column='training_id', on_delete=django.db.models.deletion.PROTECT, related_name='identified_training_needs', to='training.trainingmodule')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='training_needs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_needs',
                'ordering': ['-identified_at'],
                'indexes': [models.Index(fields=['user'], name='training_ne_user_id_61fca5_idx'), models.Index(fields=['training'], name='training_ne_trainin_88f98f_idx'), models.Index(fields=['status'], name='training_ne_status_c7f336_idx'), models.Index(fields=['priority'], name='training_ne_priorit_6182d9_idx')],
            },
        ),
    ]
