# Generated by Django 5.2.17 on 2026-08-17 16:12

import django.db.models.deletion
import django.utils.timezone
import incidents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'incident_categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('incident_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('incident_ref', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], db_index=True, default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('pos', models.ForeignKey(blank=True, db_column='pos_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='pos_security.posterminal')),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, db_column='shift_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='pos_security.posshift')),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='incidents.incidentcategory')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('evidence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(db_column='file_path', upload_to=incidents.models.incident_evidence_upload_path)),
                ('file_type', models.CharField(choices=[('Image', 'Image'), ('Document', 'Document'), ('Log', 'Log'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='incidents.incident')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_incident_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_evidence',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reported_by'], name='incidents_reporte_55408c_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['category'], name='incidents_categor_d0a1a0_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status'], name='incidents_status_9db31b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentevidence',
            index=models.Index(fields=['incident'], name='incident_ev_inciden_4ef022_idx'),
        ),
    ]
