# Generated by Django 5.2.17 on 2026-08-17 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentRiskAssessment',
            fields=[
                ('risk_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_data_involved', models.BooleanField()),
                ('pos_affected', models.BooleanField()),
                ('unauthorized_access', models.BooleanField()),
                ('business_impact', models.PositiveSmallIntegerField(choices=[(0, 'No significant business impact'), (2, 'Business operations affected')])),
                ('evidence_available', models.BooleanField()),
                ('risk_score', models.PositiveSmallIntegerField(editable=False)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_index=True, editable=False, max_length=10)),
                ('assessed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assessed_by', models.ForeignKey(db_column='assessed_by', on_delete=django.db.models.deletion.PROTECT, related_name='incident_risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_risk_assessments',
                'ordering': ['-assessed_at'],
                'indexes': [models.Index(fields=['incident'], name='incident_ri_inciden_286779_idx'), models.Index(fields=['risk_level'], name='incident_ri_risk_le_a68494_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('business_impact__in', [0, 2])), name='valid_incident_business_impact'), models.CheckConstraint(condition=models.Q(('risk_score__gte', 0), ('risk_score__lte', 12)), name='valid_incident_risk_score')],
            },
        ),
    ]
