# Generated by Django 5.2.17 on 2026-08-18 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incidentriskassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('INVESTIGATION', 'Investigation'), ('STATUS_CHANGE', 'Status Change'), ('CORRECTIVE_ACTION', 'Corrective Action'), ('RESOLUTION', 'Resolution')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(db_column='admin_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='incident_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.incident')),
            ],
            options={
                'db_table': 'incident_actions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['incident', 'created_at'], name='incident_ac_inciden_5cc710_idx'), models.Index(fields=['action_type'], name='incident_ac_action__dff705_idx'), models.Index(fields=['admin_user'], name='incident_ac_admin_u_def5b1_idx')],
            },
        ),
    ]
