# Generated by Django 5.2.17 on 2026-08-17 08:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('training_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(choices=[('POS Security', 'POS Security'), ('Password Security', 'Password Security'), ('Phishing & Social Engineering', 'Phishing & Social Engineering'), ('Incident Reporting', 'Incident Reporting'), ('Data Protection', 'Data Protection'), ('Removable Media & USB Security', 'Removable Media & USB Security')], db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], db_index=True, default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='created_training_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_modules',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTraining',
            fields=[
                ('employee_training_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Assigned', 'Assigned'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_index=True, default='Assigned', max_length=20)),
                ('progress_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(db_column='assigned_by', on_delete=django.db.models.deletion.PROTECT, related_name='training_assigned_by_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='employee_training', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(db_column='training_id', on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='training.trainingmodule')),
            ],
            options={
                'db_table': 'employee_training',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['status'], name='training_mo_status_c9e43c_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmodule',
            index=models.Index(fields=['topic'], name='training_mo_topic_3233d2_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetraining',
            index=models.Index(fields=['user'], name='employee_tr_user_id_e37f42_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetraining',
            index=models.Index(fields=['training'], name='employee_tr_trainin_264da3_idx'),
        ),
        migrations.AddIndex(
            model_name='employeetraining',
            index=models.Index(fields=['status'], name='employee_tr_status_fc15f8_idx'),
        ),
    ]
