# Generated by Django 5.2.17 on 2026-08-17 10:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('attempt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('passed', models.BooleanField()),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('assignment', models.ForeignKey(db_column='assignment_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='training.employeetraining')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['assignment'], name='quiz_attemp_assignm_7013df_idx'), models.Index(fields=['passed'], name='quiz_attemp_passed_e7138e_idx')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'attempt_number'), name='unique_assignment_attempt_number')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(blank=True, max_length=500)),
                ('option_d', models.CharField(blank=True, max_length=500)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('marks', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('training', models.ForeignKey(db_column='training_id', on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='training.trainingmodule')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['question_id'],
                'indexes': [models.Index(fields=['training'], name='quiz_questi_trainin_6d049a_idx')],
            },
        ),
    ]
